# Generated by Django 3.2.3 on 2021-05-15 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='name of the plan')),
                ('start_date', models.DateField(verbose_name='plan start date')),
                ('end_date', models.DateField(verbose_name='plan end date')),
                ('current_plan', models.BooleanField(default=False, verbose_name="owner's current plan")),
                ('description', models.TextField(blank=True, null=True, verbose_name='plan description (optional)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='training date')),
                ('training_information', models.CharField(max_length=128, verbose_name='training')),
                ('training_distance', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='total distance')),
                ('training_time', models.SmallIntegerField(verbose_name='total time')),
                ('average_speed', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='average speed [km/h]')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional notes (optional)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique_for_date='date')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='training date')),
                ('main_training', models.CharField(max_length=32)),
                ('additional_training', models.CharField(blank=True, max_length=32, null=True)),
                ('completed', models.BooleanField(default=False, verbose_name='training completed')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runapp.trainingplan', unique_for_date='date')),
            ],
        ),
    ]
